let adminWorkouts=[]; let adminUsers=[]; let editingId=null; let deletingId=null; let deleteModal=null;
$(document).ready(function(){ const currentUser=requireAdmin(); if(!currentUser)return; renderAuthNavbar("admin"); showFlashMessage(); deleteModal=new bootstrap.Modal(document.getElementById("deleteModal")); loadAdminWorkouts(); loadAdminUsers(); updateAdminChatCount(); $("#workoutForm").on("submit",e=>{e.preventDefault();handleSubmitWorkout();}); $("#resetBtn").on("click",resetForm); $("#confirmDeleteBtn").on("click",confirmDeleteWorkout); $("#adminSearchInput,#adminTypeFilter,#adminIntensityFilter,#adminUserFilter").on("input change",()=>renderWorkoutTable(getFilteredAdminWorkouts())); });
function loadAdminWorkouts(){ showLoading("#adminLoading"); getWorkouts().then(data=>{adminWorkouts=Array.isArray(data)?data:[]; updateAdminStats(adminWorkouts); renderWorkoutTable(getFilteredAdminWorkouts());}).catch(()=>showToast("Không thể tải dữ liệu","error")).finally(()=>hideLoading("#adminLoading")); }
function updateAdminStats(workouts){ $("#adminTotalWorkouts").text(workouts.length); $("#adminTotalCalories").text(formatNumber(workouts.reduce((s,w)=>s+Number(w.calories||0),0))); $("#adminTotalUsers").text(adminUsers.length || 0); }
function updateAdminChatCount(){ if(typeof getAllChatMessagesForAdmin==="function") $("#adminTotalChats").text(getAllChatMessagesForAdmin().filter(m=>m.sender==="user").length); }
function clearAdminChats(){ Object.keys(localStorage).forEach(k=>{if(k.startsWith("fittrack_chat_"))localStorage.removeItem(k)}); renderAdminChatMessages(); updateAdminChatCount(); showToast("Đã xóa lịch sử chat local","success"); }
function getFilteredAdminWorkouts(){ const kw=$("#adminSearchInput").val().toLowerCase().trim(); const type=$("#adminTypeFilter").val(); const intensity=$("#adminIntensityFilter").val(); const user=$("#adminUserFilter").val().trim(); return adminWorkouts.filter(w=>{ const content=`${w.name||""} ${w.muscleGroup||""} ${w.note||""}`.toLowerCase(); return content.includes(kw)&&(type==="all"||w.type===type)&&(intensity==="all"||w.intensity===intensity)&&(!user||String(w.userId||"")===user); }); }
function renderWorkoutTable(workouts){ const tbody=$("#workoutTableBody"); tbody.html(""); $("#adminCount").text(`${workouts.length} buổi`); if(!workouts.length){$("#adminEmpty").removeClass("d-none");return;} $("#adminEmpty").addClass("d-none"); workouts.forEach(w=>tbody.append(`<tr><td><div class="d-flex align-items-center gap-2"><div class="table-workout-icon">${getTypeIcon(w.type)}</div><div><div class="fw-bold">${w.name||"Không có tên"}</div><small class="text-muted">${w.note||"Không có ghi chú"}</small></div></div></td><td><span class="badge text-bg-light">${getUserNameById(w.userId)}</span></td><td><span class="badge type-badge ${getTypeBadgeClass(w.type)}">${w.type||"Other"}</span></td><td><span class="badge ${getIntensityClass(w.intensity)}">${w.intensity||"--"}</span></td><td><small>💤 ${w.sleepHours||"--"}h • 💧 ${w.waterLiters||"--"}L<br>⚖️ ${w.weightToday||"--"}kg • ${w.mood||"--"}</small></td><td>${formatDate(w.date)}</td><td class="text-end table-actions"><button class="btn btn-sm btn-outline-primary" onclick="startEditWorkout('${w.id}')">Sửa</button><button class="btn btn-sm btn-outline-danger" onclick="openDeleteModal('${w.id}')">Xóa</button></td></tr>`)); }
function getFormData(){ const old=adminWorkouts.find(w=>String(w.id)===String(editingId))||{}; return { ...old, name:$("#name").val().trim(), type:$("#type").val(), muscleGroup:$("#muscleGroup").val().trim(), duration:Number($("#duration").val()), calories:Number($("#calories").val()), date:$("#date").val(), intensity:$("#intensity").val(), mood:$("#mood").val(), sleepHours:Number($("#sleepHours").val()||0), waterLiters:Number($("#waterLiters").val()||0), weightToday:Number($("#weightToday").val()||0), note:$("#note").val().trim(), updatedAt:nowISOString(), createdAt:old.createdAt||nowISOString() }; }
function handleSubmitWorkout(){ clearErrors(); const data=getFormData(); const validation=validateWorkoutForm(data); if(!validation.isValid){Object.keys(validation.errors).forEach(f=>showFieldError(f,validation.errors[f])); return showToast("Vui lòng kiểm tra form","error");} $("#submitBtn").prop("disabled",true).text("Đang lưu..."); const action=editingId?updateWorkout(editingId,data):createWorkout(data); action.then(()=>{showToast(editingId?"Cập nhật thành công":"Thêm thành công","success"); resetForm(); loadAdminWorkouts();}).catch(()=>showToast("Thao tác thất bại","error")).finally(()=>$("#submitBtn").prop("disabled",false).text("Lưu buổi tập")); }
function startEditWorkout(id){ const w=adminWorkouts.find(i=>String(i.id)===String(id)); if(!w)return; editingId=w.id; clearErrors(); $("#formTitle").text("Chỉnh sửa buổi tập"); $("#formModeBadge").text("Edit").addClass("editing"); $("#workoutId").val(w.id); ["name","type","muscleGroup","duration","calories","date","intensity","mood","sleepHours","waterLiters","weightToday","note"].forEach(k=>$("#"+k).val(w[k]||"")); $("html, body").animate({scrollTop:0},250); }
function resetForm(){ editingId=null; clearErrors(); $("#formTitle").text("Thêm buổi tập"); $("#formModeBadge").text("New").removeClass("editing"); $("#workoutForm")[0].reset(); $("#workoutId").val(""); }
function openDeleteModal(id){ deletingId=id; deleteModal.show(); }
function confirmDeleteWorkout(){ if(!deletingId)return; $("#confirmDeleteBtn").prop("disabled",true).text("Đang xóa..."); deleteWorkout(deletingId).then(()=>{showToast("Xóa thành công","success"); deleteModal.hide(); deletingId=null; loadAdminWorkouts();}).catch(()=>showToast("Không thể xóa","error")).finally(()=>$("#confirmDeleteBtn").prop("disabled",false).text("Xóa")); }


// ===== Phase 8: Admin user management =====
function loadAdminUsers(){
  getUsers().then(function(users){ adminUsers=Array.isArray(users)?users:[]; $("#adminTotalUsers").text(adminUsers.length); renderAdminUsers(); updateAdminStats(adminWorkouts); })
  .catch(()=>showToast("Không thể tải danh sách người dùng","error"));
}
function getUserNameById(id){ const u=adminUsers.find(x=>String(x.id)===String(id)); return u ? (u.fullName || u.email) : (id || "--"); }
function renderAdminUsers(){
  const tbody=$("#adminUserTableBody"); if(!tbody.length)return; const kw=($("#adminUserSearch").val()||"").toLowerCase().trim(); tbody.html("");
  const data=adminUsers.filter(u=>`${u.fullName||""} ${u.email||""} ${u.phone||""} ${u.goal||""}`.toLowerCase().includes(kw));
  $("#adminUserEmpty").toggleClass("d-none", data.length>0);
  data.forEach(u=>tbody.append(`<tr><td><div class="fw-bold">${u.fullName||"Chưa cập nhật"}</div><small class="text-muted">ID: ${u.id}</small></td><td>${u.email||"--"}<br><small class="text-muted">${u.phone||"Chưa có SĐT"}</small></td><td>${u.goal||"--"}<br><small class="text-muted">${u.height||"--"}cm • ${u.weight||"--"}kg</small></td><td><span class="badge ${u.role==="admin"?"text-bg-dark":"text-bg-success"}">${u.role||"user"}</span></td><td>${formatDateTime(u.createdAt)}</td><td>${u.lastLoginAt?formatDateTime(u.lastLoginAt):"Chưa có"}</td></tr>`));
}

// ===== Phase 8: Admin articles =====
function renderAdminArticles(){
  const list=$("#adminArticleList"); if(!list.length)return; const articles=getFitTrackArticles(true); $("#articleCount").text(`${articles.length} bài`);
  list.html(articles.map(a=>`<div class="profile-workout-item"><div><div class="fw-bold">${a.title}</div><small class="text-muted">${a.category} • ${formatDateTime(a.createdAt)} • ${a.status==="hidden"?"Đang ẩn":"Đang hiện"}</small></div><div class="table-actions"><button class="btn btn-sm btn-outline-primary" onclick="editAdminArticle('${a.id}')">Sửa</button><button class="btn btn-sm btn-outline-danger" onclick="deleteAdminArticle('${a.id}')">Xóa</button></div></div>`).join(""));
}
function resetArticleForm(){ $("#articleForm")[0]?.reset(); $("#articleId").val(""); $("#articleSubmitBtn").text("Lưu bài viết"); }
function saveAdminArticle(event){ event.preventDefault(); const articles=getFitTrackArticles(true); const id=$("#articleId").val()||`a${Date.now()}`; const old=articles.find(a=>a.id===id); const item={ id, title:$("#articleTitle").val().trim(), category:$("#articleCategoryInput").val(), summary:$("#articleSummary").val().trim(), content:$("#articleContent").val().trim(), status:$("#articleStatus").val(), createdAt:old?.createdAt||nowISOString(), updatedAt:nowISOString()}; if(!item.title||!item.summary||!item.content)return showToast("Vui lòng nhập đủ nội dung bài viết","error"); const next=old?articles.map(a=>a.id===id?item:a):[item,...articles]; saveFitTrackArticles(next); resetArticleForm(); renderAdminArticles(); showToast("Đã lưu bài viết","success"); }
function editAdminArticle(id){ const a=getFitTrackArticles(true).find(x=>x.id===id); if(!a)return; $("#articleId").val(a.id); $("#articleTitle").val(a.title); $("#articleCategoryInput").val(a.category); $("#articleSummary").val(a.summary); $("#articleContent").val(a.content); $("#articleStatus").val(a.status||"visible"); $("#articleSubmitBtn").text("Cập nhật bài viết"); }
function deleteAdminArticle(id){ if(!confirm("Xóa bài viết này?"))return; saveFitTrackArticles(getFitTrackArticles(true).filter(a=>a.id!==id)); renderAdminArticles(); showToast("Đã xóa bài viết","success"); }

// ===== Phase 8: Admin reports =====
function renderAdminReports(){
  const box=$("#adminReports"); if(!box.length)return; const real=calculateWorkoutTimeStats(adminWorkouts); const weekly=adminWorkouts.filter(w=>isThisWeek(w.date)); const activeUsers=new Set(weekly.map(w=>w.userId).filter(Boolean)).size; const completed=adminWorkouts.filter(w=>w.completed===true || w.completed==="true").length; const completeRate=adminWorkouts.length?Math.round(completed/adminWorkouts.length*100):0;
  box.html(`
    <div class="col-md-3"><div class="admin-stat-card"><small>Hôm nay</small><strong>${real.todayCount}</strong><span>buổi tập</span></div></div>
    <div class="col-md-3"><div class="admin-stat-card"><small>Tháng này</small><strong>${real.monthCount}</strong><span>buổi tập</span></div></div>
    <div class="col-md-3"><div class="admin-stat-card"><small>User hoạt động tuần</small><strong>${activeUsers}</strong><span>người dùng</span></div></div>
    <div class="col-md-3"><div class="admin-stat-card"><small>Tỷ lệ hoàn thành</small><strong>${completeRate}%</strong><span>workout completed</span></div></div>
    <div class="col-12"><div class="progress-chart mt-3">${getDailyWorkoutSummary(adminWorkouts,7).map(d=>createAdminReportRow(formatDate(d.date), d.count, "buổi", Math.min(100,d.count*25))).join("")}</div></div>`);
  setTimeout(()=>$(".chart-bar").each(function(){ $(this).css("width", $(this).data("width")); }),100);
}
function createAdminReportRow(label,value,unit,percent){ return `<div class="chart-row"><div class="chart-label">${label}</div><div class="chart-track"><div class="chart-bar" data-width="${percent}%"></div></div><div class="chart-value">${value} ${unit}</div></div>`; }
