const FITTRACK_ARTICLES_KEY = "fittrack_articles";
const DEFAULT_ARTICLES = [
  { id:"a1", title:"Cách duy trì thói quen tập luyện đều đặn", category:"Thói quen", summary:"Bắt đầu nhỏ, ghi nhật ký mỗi ngày và theo dõi tiến độ theo tuần thay vì chỉ nhìn kết quả tức thì.", content:"Hãy bắt đầu với các buổi tập ngắn 15-20 phút, chọn khung giờ cố định và ghi lại cảm nhận sau tập. FitTrack giúp bạn nhìn lại số buổi, phút tập, calo, giấc ngủ và nước uống để điều chỉnh thói quen.", createdAt:"2026-05-23T08:00:00.000Z", status:"visible" },
  { id:"a2", title:"Theo dõi giấc ngủ và nước uống khi tập luyện", category:"Sức khỏe", summary:"Giấc ngủ và nước uống ảnh hưởng đến cảm giác trong buổi tập, nên ghi lại cùng nhật ký workout.", content:"Khi ghi nhật ký tập, bạn nên thêm giờ ngủ và lượng nước uống. Đây là dữ liệu hỗ trợ để hiểu vì sao một ngày tập tốt hoặc chưa tốt. Thông tin này chỉ mang tính tham khảo cá nhân.", createdAt:"2026-05-23T08:10:00.000Z", status:"visible" },
  { id:"a3", title:"BMI là gì và nên hiểu thế nào?", category:"Chỉ số", summary:"BMI là chỉ số tham khảo dựa trên chiều cao và cân nặng, không thay thế đánh giá chuyên môn.", content:"BMI được tính bằng cân nặng chia cho bình phương chiều cao. Trong FitTrack, BMI chỉ là chỉ số tham khảo để người dùng tự theo dõi xu hướng sức khỏe cá nhân cùng các chỉ số khác như thời gian tập, giấc ngủ và nước uống.", createdAt:"2026-05-23T08:20:00.000Z", status:"visible" },
  { id:"a4", title:"Gợi ý chọn cường độ tập phù hợp", category:"Tập luyện", summary:"Cường độ nhẹ, vừa, cao nên được chọn theo cảm giác, lịch sử tập và giấc ngủ gần nhất.", content:"Nếu hôm trước tập cường độ cao hoặc ngủ ít, bạn có thể chọn bài nhẹ hơn như đi bộ hoặc yoga. Nếu duy trì ổn định, hãy tăng dần thời lượng hoặc độ khó từng chút một.", createdAt:"2026-05-23T08:30:00.000Z", status:"visible" }
];
function seedDefaultArticles(){ if(!localStorage.getItem(FITTRACK_ARTICLES_KEY)) localStorage.setItem(FITTRACK_ARTICLES_KEY, JSON.stringify(DEFAULT_ARTICLES)); }
function getFitTrackArticles(includeHidden=false){ seedDefaultArticles(); try { const items=JSON.parse(localStorage.getItem(FITTRACK_ARTICLES_KEY))||[]; return includeHidden ? items : items.filter(a=>a.status!=="hidden"); } catch { return DEFAULT_ARTICLES; } }
function saveFitTrackArticles(items){ localStorage.setItem(FITTRACK_ARTICLES_KEY, JSON.stringify(items)); }
function renderArticlesPage(){ const wrap=$("#articlesList"); if(!wrap.length)return; const kw=$("#articleSearch").val()?.toLowerCase().trim()||""; const cat=$("#articleCategory").val()||"all"; const articles=getFitTrackArticles().filter(a=>`${a.title} ${a.summary} ${a.content}`.toLowerCase().includes(kw)&&(cat==="all"||a.category===cat)); if(!articles.length){ wrap.html(`<div class="empty-box text-center py-5"><h3 class="h5 fw-bold">Chưa có bài viết phù hợp</h3><p class="text-muted">Thử đổi từ khóa hoặc danh mục.</p></div>`); return; } wrap.html(articles.map(a=>`<article id="article-${a.id}" class="card article-detail-card mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between flex-wrap gap-2 mb-2"><span class="badge bg-success-subtle text-success-emphasis">${a.category}</span><small class="text-muted">${formatDateTime(a.createdAt)}</small></div><h2 class="h4 fw-black">${a.title}</h2><p class="text-muted">${a.summary}</p><p class="mb-0">${a.content}</p></div></article>`).join("")); }
function initArticlesPage(){ const u=requireLogin(); if(!u)return; renderAuthNavbar("articles"); showFlashMessage(); renderArticlesPage(); $("#articleSearch,#articleCategory").on("input change", renderArticlesPage); }
